### ISSUE TITLE
repurposing your repo for my own needs

### ISSUE THREAD

**Issue by techie2000** [ehllie/dotfiles#3]
"If you see me doing something stupid or hard to understand, feel free to open an issue."

Hi,
I've been playing around with nixos for the first time this past week and looking at multiple repos for inspiration for how to structure my project to give me the flexibility I'm seeking for future builds.

In your project, is nixos-modules effectively the configuration.nix and nixos-configurations effectively the hardware-configuration.nix that would otherwise have been generated with a base installation?

On other repos the hosts/*.nix files are very similar, reflecting the use of default.nix and then a small handful of machine specific tweaks, and this is what I would expect and look to recreate. However your two nixos-configurations/*.nix are very different. Are your hosts really that different, or is there some other reason/logic that I'm not seeing? 

I'm looking to use nixos as the basis of vm's/containers going forward so would expect to have a lot of small nixos-modules referencing a default/common.nix, and then a small number of nixos-configurations as the underlying hardware will be common.

Any pointers on the use of sops for secrets? I've never used that before :)

Are you using ante in the nixos setup/configuration or is that for your use post installation only? I've never used that either and am wondering what it does as an input in your flake rather than just being installed as pkgs.ante? (I guess the same question holds for yazi, and possibly sops as well - although I can believe that the nixos build would need sops secrets so would explain why it's an input)

I've not come across flake-parts/ez-configs in any of the other half dozen or so projects I've been taking inspiration from. Those projects have LOTS of modularity...so I'm wondering what benefit your see from using these two?

Unrelated to my questions/queries, but as a thought, maybe consider turning on the 'discussions' feature of github for this type of non-issue :)

**Comment by ehllie** [comment]
> In your project, is nixos-modules effectively the configuration.nix and nixos-configurations effectively the hardware-configuration.nix that would otherwise have been generated with a base installation?

This repository uses the nix flake framework I've made, [ez-configs](https://github.com/ehllie/ez-configs). The gist of it, is that `nixos-modules` includes resuable modules, that can then be imported into individual machines inside `nixos-configurations`. The contents of `hardware-configuration.nix` would indeed fit better into `nixos-configurations`, but any host specific things would go there. The naming scheme reflects the names of flake outputs. For more details check that repository.

> However your two nixos-configurations/.nix are very different. Are your hosts really that different, or is there some other reason/logic that I'm not seeing?

My two nixos hosts are quite different, since `dell-builder` is a server, while `dell-gram` is a workstation system. I've stopped using nixos as a workstation over a year a go, and have been using macos instead. That's why most of my recent changes have been inside `darwin-`/`home-` `modules`/`configurations`. 

> Are you using ante in the nixos setup/configuration or is that for your use post installation only? I've never used that either and am wondering what it does as an input in your flake rather than just being installed as pkgs.ante? (I guess the same question holds for yazi, and possibly sops as well - although I can believe that the nixos build would need sops secrets so would explain why it's an input)

I'm using ante/ yazi/ nil as flake inputs to get the most [recent versions of those programs](https://github.com/ehllie/dotfiles/blob/bc705248c9de1666b7915e605610b6e23ad709ce/overlays/default.nix#L18-L20) directly from their git repositories, rather then the one in nixpkgs. sops-nix flake provides [modules](https://github.com/ehllie/dotfiles/blob/bc705248c9de1666b7915e605610b6e23ad709ce/nixos-configurations/dell-builder.nix#L5) for [managing runtime secrets with nix](https://github.com/ehllie/dotfiles/blob/bc705248c9de1666b7915e605610b6e23ad709ce/nixos-configurations/dell-builder.nix#L44-L50).

> I've not come across flake-parts/ez-configs in any of the other half dozen or so projects I've been taking inspiration from. Those projects have LOTS of modularity...so I'm wondering what benefit your see from using these two?

I'm using `flake-parts` and `ez-configs` because the former makes your flake modular just like nixos modules, and the latter lets you structure your flake outputs using the directory structure rather than with glue nix code.

> Unrelated to my questions/queries, but as a thought, maybe consider turning on the 'discussions' feature of github for this type of non-issue :)

I've enabled discussions if you or anyone else prefers to use that feature rather than issues. It's not like issues in this kind of repository mean much anyway, so it's fine to use either.
